# -*- coding: utf-8 -*-
"""Model1_Deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gSZmDozr3KuPgWXiCFH2beYVjFVnIiXb
"""

!pip install streamlit python-dotenv google-genai pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("2zoVyqgR5PfHZNxWggo8i7PJH0R_XSNBnN41EVvCpy3bJthX")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile .env
# GEMINI_API_KEY = "AIzaSyB424pVCvaerRhL5ZGuc73rKpJ2GU9dKkI"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# from google import genai
# from dotenv import load_dotenv
# import os
# 
# load_dotenv()
# API_KEY = os.getenv("GEMINI_API_KEY")
# 
# if not API_KEY:
#   st.error("Missing GEMINI_API_KEY in env.file. Please add it and restart the app.")
# 
#   st.stop()
# 
# client = genai.Client(api_key=API_KEY)
# MODEL_NAME = "models/gemini-2.5-flash"
# 
# st.set_page_config(page_title="PersonalBot", layout="centered")
# st.title("PersonalBot")
# st.markdown("An intelligent assistant powered by **Gemini** and **Streamlit**.")
# 
# if "history" not in st.session_state:
#   st.session_state.history = []
# 
# def get_gemini_response(prompt):
#   response = client.models.generate_content(
#       model = MODEL_NAME,
#       contents = prompt
#   )
#   return response.text
# 
# for role, msg in st.session_state.history:
#   if role == "user":
#     st.markdown(f"**You:** {msg}")
#   else:
#     st.markdown(f"**Bot:** {msg}")
# 
# user_input = st.text_input("Your message:")
# 
# if st.button("Send"):
#   if user_input.strip():
#     st.session_state.history.append(("user", user_input))
#     with st.spinner("Generating response..."):
#       try:
#         bot_response = get_gemini_response(user_input)
#       except Exception as e:
#         bot_response = f"error : {e}"
# 
#     st.session_state.history.append(("bot", bot_response))
#     st.rerun()
# 
#   else:
#     st.warning("Please enter a message before sending.")

from pyngrok import ngrok

ngrok.kill()

public_url = ngrok.connect(8501)
print("Your Streamlit App Url: ", public_url)

!streamlit run app.py &/dev/null&